services:
  - type: web
    name: salonity-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn salonity.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: salonity-db
          property: connectionString
    databases:
      - name: salonity-db
        databaseName: salonity
        user: salonity 